---
dependency:
  name: galaxy
driver:
  name: docker
platforms:

  - name: CentOS-8
    image: centos:8
    pre_build_image: true
  - name: CentOS-7
    image: centos:7
    pre_build_image: true

  - name: Debian-10
    image: debian:10
    pre_build_image: true
  - name: Debian-9
    image: debian:9
    pre_build_image: true

  - name: Ubuntu_20.04
    image: ubuntu:focal
    pre_build_image: true
  - name: Ubuntu_20.10
    image: ubuntu:groovy
    pre_build_image: true
  - name: Ubuntu_18.04
    image: ubuntu:bionic
    pre_build_image: true

# TODO - Support Ubuntu21.04
#  - name: Ubuntu_21.04
#    image: ubuntu:hirsute
#    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint .
