---
name: Build & Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker setup
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install -y ansible ansible-lint
          python3 -m pip install --upgrade --user setuptools
          python3 -m pip install "molecule[ansible]"
          python3 -m pip install --user "molecule[docker,lint]"
      - name: Test with molecule
        run: |
          molecule test
